### PR TITLE
Add hg support

### PR DESCRIPTION
**Pull request by royallthefourth**
Added tests, tasks, and documentation for Mercurial

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
This looks pretty cool. With this PR, we now have three VCS mechanisms that operate via a very similar API.  Perhaps we should add an appropriate VCS interface for each of these tasks to implement, to formalize what the least-common-denominator behavior is between the mechanisms.  This would allow folks to write VCS-agnostic operations, which might be useful for some.

**Comment by royallthefourth** [comment]
I like that idea! After this gets merged, I'd be happy to write such an interface and adapt these VCS classes to work with it.

Also, how can I contribute to getting 1.0 out the door? Is it just the globbing feature and documentation remaining or does the milestone need to be updated?

**Comment by greg-1-anderson** [comment]
+1 for merging this PR as-is and adding an interface as a follow-on task.

I don't think that the globbing feature should be a blocker for 1.0; we will need some documentation updates, but not everything mentioned in that issue necessarily needs to be done prior to the stable release. There are some potential b/c breaking changes in #377 that we may or may not choose to make.  Exact requirements for 1.0 are up to @DavertMik; hopefully we will get there soon.

**Comment by DavertMik** [comment]
Great! Thank you very much!

**Pull request merged**
