### PR TITLE
Updating Namespace reference in Watch task

### PR DESCRIPTION
**Pull request by t73biz**
Updating Namespace for Watch task, refering to Lurker\ResourceWatcher\ResourceWatcher

Relates to Issue #363

### CODE REVIEW

**Comment by bangpound** [comment]
aww darn… i didn't see this before i opened #372. closing that now!

**Comment by bangpound** [comment]
What do we need to do to get this PR merged?

**Comment by t73biz** [comment]
It is a very simple fix. Should be no problem to merge in at all.

**Comment by DavertMik** [comment]
yeah, thank you. Sorry for the delay

**Pull request merged**
